apiVersion: v1
kind: Service
metadata:
  name: react-todo-app-service
spec:
  selector:
    app: react-todo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
